/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated.app'
import { Route as AuthenticatedAppShowcaseRouteImport } from './routes/_authenticated.app.showcase'
import { Route as AuthenticatedAppResourcesRouteImport } from './routes/_authenticated.app.resources'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated.app.profile'
import { Route as AuthenticatedAppOnboardingRouteImport } from './routes/_authenticated.app.onboarding'
import { Route as AuthenticatedAppMessagesRouteImport } from './routes/_authenticated.app.messages'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated.app.leaderboard'
import { Route as AuthenticatedAppIdeasRouteImport } from './routes/_authenticated.app.ideas'
import { Route as AuthenticatedAppHallRouteImport } from './routes/_authenticated.app.hall'
import { Route as AuthenticatedAppFeedRouteImport } from './routes/_authenticated.app.feed'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated.app.dashboard'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated.app.community'
import { Route as AuthenticatedAppCofoundersRouteImport } from './routes/_authenticated.app.cofounders'
import { Route as AuthenticatedAppChallengesRouteImport } from './routes/_authenticated.app.challenges'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated.app.admin'
import { Route as AuthenticatedAppUUserIdRouteImport } from './routes/_authenticated.app.u.$userId'
import { Route as AuthenticatedAppMessagesUserIdRouteImport } from './routes/_authenticated.app.messages.$userId'
import { Route as AuthenticatedAppCommunityGroupIdRouteImport } from './routes/_authenticated.app.community.$groupId'
import { Route as AuthenticatedAppCofoundersRequestsRouteImport } from './routes/_authenticated.app.cofounders.requests'
import { Route as AuthenticatedAppChallengesRequestsRouteImport } from './routes/_authenticated.app.challenges.requests'
import { Route as AuthenticatedAppChallengesIdRouteImport } from './routes/_authenticated.app.challenges.$id'
import { Route as AuthenticatedAppAdminRequestsRouteImport } from './routes/_authenticated.app.admin.requests'
import { Route as AuthenticatedAppAdminChallengesRouteImport } from './routes/_authenticated.app.admin.challenges'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppShowcaseRoute =
  AuthenticatedAppShowcaseRouteImport.update({
    id: '/showcase',
    path: '/showcase',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppResourcesRoute =
  AuthenticatedAppResourcesRouteImport.update({
    id: '/resources',
    path: '/resources',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOnboardingRoute =
  AuthenticatedAppOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppMessagesRoute =
  AuthenticatedAppMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIdeasRoute = AuthenticatedAppIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppHallRoute = AuthenticatedAppHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFeedRoute = AuthenticatedAppFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCofoundersRoute =
  AuthenticatedAppCofoundersRouteImport.update({
    id: '/cofounders',
    path: '/cofounders',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppChallengesRoute =
  AuthenticatedAppChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppUUserIdRoute = AuthenticatedAppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppMessagesUserIdRoute =
  AuthenticatedAppMessagesUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAppMessagesRoute,
  } as any)
const AuthenticatedAppCommunityGroupIdRoute =
  AuthenticatedAppCommunityGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => AuthenticatedAppCommunityRoute,
  } as any)
const AuthenticatedAppCofoundersRequestsRoute =
  AuthenticatedAppCofoundersRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppCofoundersRoute,
  } as any)
const AuthenticatedAppChallengesRequestsRoute =
  AuthenticatedAppChallengesRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppChallengesRoute,
  } as any)
const AuthenticatedAppChallengesIdRoute =
  AuthenticatedAppChallengesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAppChallengesRoute,
  } as any)
const AuthenticatedAppAdminRequestsRoute =
  AuthenticatedAppAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminChallengesRoute =
  AuthenticatedAppAdminChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/challenges': typeof AuthenticatedAppChallengesRouteWithChildren
  '/app/cofounders': typeof AuthenticatedAppCofoundersRouteWithChildren
  '/app/community': typeof AuthenticatedAppCommunityRouteWithChildren
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/hall': typeof AuthenticatedAppHallRoute
  '/app/ideas': typeof AuthenticatedAppIdeasRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/resources': typeof AuthenticatedAppResourcesRoute
  '/app/showcase': typeof AuthenticatedAppShowcaseRoute
  '/app/admin/challenges': typeof AuthenticatedAppAdminChallengesRoute
  '/app/admin/requests': typeof AuthenticatedAppAdminRequestsRoute
  '/app/challenges/$id': typeof AuthenticatedAppChallengesIdRoute
  '/app/challenges/requests': typeof AuthenticatedAppChallengesRequestsRoute
  '/app/cofounders/requests': typeof AuthenticatedAppCofoundersRequestsRoute
  '/app/community/$groupId': typeof AuthenticatedAppCommunityGroupIdRoute
  '/app/messages/$userId': typeof AuthenticatedAppMessagesUserIdRoute
  '/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/challenges': typeof AuthenticatedAppChallengesRouteWithChildren
  '/app/cofounders': typeof AuthenticatedAppCofoundersRouteWithChildren
  '/app/community': typeof AuthenticatedAppCommunityRouteWithChildren
  '/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/app/feed': typeof AuthenticatedAppFeedRoute
  '/app/hall': typeof AuthenticatedAppHallRoute
  '/app/ideas': typeof AuthenticatedAppIdeasRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/resources': typeof AuthenticatedAppResourcesRoute
  '/app/showcase': typeof AuthenticatedAppShowcaseRoute
  '/app/admin/challenges': typeof AuthenticatedAppAdminChallengesRoute
  '/app/admin/requests': typeof AuthenticatedAppAdminRequestsRoute
  '/app/challenges/$id': typeof AuthenticatedAppChallengesIdRoute
  '/app/challenges/requests': typeof AuthenticatedAppChallengesRequestsRoute
  '/app/cofounders/requests': typeof AuthenticatedAppCofoundersRequestsRoute
  '/app/community/$groupId': typeof AuthenticatedAppCommunityGroupIdRoute
  '/app/messages/$userId': typeof AuthenticatedAppMessagesUserIdRoute
  '/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/challenges': typeof AuthenticatedAppChallengesRouteWithChildren
  '/_authenticated/app/cofounders': typeof AuthenticatedAppCofoundersRouteWithChildren
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRouteWithChildren
  '/_authenticated/app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/app/feed': typeof AuthenticatedAppFeedRoute
  '/_authenticated/app/hall': typeof AuthenticatedAppHallRoute
  '/_authenticated/app/ideas': typeof AuthenticatedAppIdeasRoute
  '/_authenticated/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/app/messages': typeof AuthenticatedAppMessagesRouteWithChildren
  '/_authenticated/app/onboarding': typeof AuthenticatedAppOnboardingRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/resources': typeof AuthenticatedAppResourcesRoute
  '/_authenticated/app/showcase': typeof AuthenticatedAppShowcaseRoute
  '/_authenticated/app/admin/challenges': typeof AuthenticatedAppAdminChallengesRoute
  '/_authenticated/app/admin/requests': typeof AuthenticatedAppAdminRequestsRoute
  '/_authenticated/app/challenges/$id': typeof AuthenticatedAppChallengesIdRoute
  '/_authenticated/app/challenges/requests': typeof AuthenticatedAppChallengesRequestsRoute
  '/_authenticated/app/cofounders/requests': typeof AuthenticatedAppCofoundersRequestsRoute
  '/_authenticated/app/community/$groupId': typeof AuthenticatedAppCommunityGroupIdRoute
  '/_authenticated/app/messages/$userId': typeof AuthenticatedAppMessagesUserIdRoute
  '/_authenticated/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/admin'
    | '/app/challenges'
    | '/app/cofounders'
    | '/app/community'
    | '/app/dashboard'
    | '/app/feed'
    | '/app/hall'
    | '/app/ideas'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/resources'
    | '/app/showcase'
    | '/app/admin/challenges'
    | '/app/admin/requests'
    | '/app/challenges/$id'
    | '/app/challenges/requests'
    | '/app/cofounders/requests'
    | '/app/community/$groupId'
    | '/app/messages/$userId'
    | '/app/u/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/app'
    | '/app/admin'
    | '/app/challenges'
    | '/app/cofounders'
    | '/app/community'
    | '/app/dashboard'
    | '/app/feed'
    | '/app/hall'
    | '/app/ideas'
    | '/app/leaderboard'
    | '/app/messages'
    | '/app/onboarding'
    | '/app/profile'
    | '/app/resources'
    | '/app/showcase'
    | '/app/admin/challenges'
    | '/app/admin/requests'
    | '/app/challenges/$id'
    | '/app/challenges/requests'
    | '/app/cofounders/requests'
    | '/app/community/$groupId'
    | '/app/messages/$userId'
    | '/app/u/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/app'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/challenges'
    | '/_authenticated/app/cofounders'
    | '/_authenticated/app/community'
    | '/_authenticated/app/dashboard'
    | '/_authenticated/app/feed'
    | '/_authenticated/app/hall'
    | '/_authenticated/app/ideas'
    | '/_authenticated/app/leaderboard'
    | '/_authenticated/app/messages'
    | '/_authenticated/app/onboarding'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/resources'
    | '/_authenticated/app/showcase'
    | '/_authenticated/app/admin/challenges'
    | '/_authenticated/app/admin/requests'
    | '/_authenticated/app/challenges/$id'
    | '/_authenticated/app/challenges/requests'
    | '/_authenticated/app/cofounders/requests'
    | '/_authenticated/app/community/$groupId'
    | '/_authenticated/app/messages/$userId'
    | '/_authenticated/app/u/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/showcase': {
      id: '/_authenticated/app/showcase'
      path: '/showcase'
      fullPath: '/app/showcase'
      preLoaderRoute: typeof AuthenticatedAppShowcaseRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/resources': {
      id: '/_authenticated/app/resources'
      path: '/resources'
      fullPath: '/app/resources'
      preLoaderRoute: typeof AuthenticatedAppResourcesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/onboarding': {
      id: '/_authenticated/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AuthenticatedAppOnboardingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/messages': {
      id: '/_authenticated/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AuthenticatedAppMessagesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leaderboard': {
      id: '/_authenticated/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ideas': {
      id: '/_authenticated/app/ideas'
      path: '/ideas'
      fullPath: '/app/ideas'
      preLoaderRoute: typeof AuthenticatedAppIdeasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hall': {
      id: '/_authenticated/app/hall'
      path: '/hall'
      fullPath: '/app/hall'
      preLoaderRoute: typeof AuthenticatedAppHallRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feed': {
      id: '/_authenticated/app/feed'
      path: '/feed'
      fullPath: '/app/feed'
      preLoaderRoute: typeof AuthenticatedAppFeedRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/dashboard': {
      id: '/_authenticated/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cofounders': {
      id: '/_authenticated/app/cofounders'
      path: '/cofounders'
      fullPath: '/app/cofounders'
      preLoaderRoute: typeof AuthenticatedAppCofoundersRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/challenges': {
      id: '/_authenticated/app/challenges'
      path: '/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AuthenticatedAppChallengesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/u/$userId': {
      id: '/_authenticated/app/u/$userId'
      path: '/u/$userId'
      fullPath: '/app/u/$userId'
      preLoaderRoute: typeof AuthenticatedAppUUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/messages/$userId': {
      id: '/_authenticated/app/messages/$userId'
      path: '/$userId'
      fullPath: '/app/messages/$userId'
      preLoaderRoute: typeof AuthenticatedAppMessagesUserIdRouteImport
      parentRoute: typeof AuthenticatedAppMessagesRoute
    }
    '/_authenticated/app/community/$groupId': {
      id: '/_authenticated/app/community/$groupId'
      path: '/$groupId'
      fullPath: '/app/community/$groupId'
      preLoaderRoute: typeof AuthenticatedAppCommunityGroupIdRouteImport
      parentRoute: typeof AuthenticatedAppCommunityRoute
    }
    '/_authenticated/app/cofounders/requests': {
      id: '/_authenticated/app/cofounders/requests'
      path: '/requests'
      fullPath: '/app/cofounders/requests'
      preLoaderRoute: typeof AuthenticatedAppCofoundersRequestsRouteImport
      parentRoute: typeof AuthenticatedAppCofoundersRoute
    }
    '/_authenticated/app/challenges/requests': {
      id: '/_authenticated/app/challenges/requests'
      path: '/requests'
      fullPath: '/app/challenges/requests'
      preLoaderRoute: typeof AuthenticatedAppChallengesRequestsRouteImport
      parentRoute: typeof AuthenticatedAppChallengesRoute
    }
    '/_authenticated/app/challenges/$id': {
      id: '/_authenticated/app/challenges/$id'
      path: '/$id'
      fullPath: '/app/challenges/$id'
      preLoaderRoute: typeof AuthenticatedAppChallengesIdRouteImport
      parentRoute: typeof AuthenticatedAppChallengesRoute
    }
    '/_authenticated/app/admin/requests': {
      id: '/_authenticated/app/admin/requests'
      path: '/requests'
      fullPath: '/app/admin/requests'
      preLoaderRoute: typeof AuthenticatedAppAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/challenges': {
      id: '/_authenticated/app/admin/challenges'
      path: '/challenges'
      fullPath: '/app/admin/challenges'
      preLoaderRoute: typeof AuthenticatedAppAdminChallengesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminChallengesRoute: typeof AuthenticatedAppAdminChallengesRoute
  AuthenticatedAppAdminRequestsRoute: typeof AuthenticatedAppAdminRequestsRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminChallengesRoute: AuthenticatedAppAdminChallengesRoute,
  AuthenticatedAppAdminRequestsRoute: AuthenticatedAppAdminRequestsRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppChallengesRouteChildren {
  AuthenticatedAppChallengesIdRoute: typeof AuthenticatedAppChallengesIdRoute
  AuthenticatedAppChallengesRequestsRoute: typeof AuthenticatedAppChallengesRequestsRoute
}

const AuthenticatedAppChallengesRouteChildren: AuthenticatedAppChallengesRouteChildren =
  {
    AuthenticatedAppChallengesIdRoute: AuthenticatedAppChallengesIdRoute,
    AuthenticatedAppChallengesRequestsRoute:
      AuthenticatedAppChallengesRequestsRoute,
  }

const AuthenticatedAppChallengesRouteWithChildren =
  AuthenticatedAppChallengesRoute._addFileChildren(
    AuthenticatedAppChallengesRouteChildren,
  )

interface AuthenticatedAppCofoundersRouteChildren {
  AuthenticatedAppCofoundersRequestsRoute: typeof AuthenticatedAppCofoundersRequestsRoute
}

const AuthenticatedAppCofoundersRouteChildren: AuthenticatedAppCofoundersRouteChildren =
  {
    AuthenticatedAppCofoundersRequestsRoute:
      AuthenticatedAppCofoundersRequestsRoute,
  }

const AuthenticatedAppCofoundersRouteWithChildren =
  AuthenticatedAppCofoundersRoute._addFileChildren(
    AuthenticatedAppCofoundersRouteChildren,
  )

interface AuthenticatedAppCommunityRouteChildren {
  AuthenticatedAppCommunityGroupIdRoute: typeof AuthenticatedAppCommunityGroupIdRoute
}

const AuthenticatedAppCommunityRouteChildren: AuthenticatedAppCommunityRouteChildren =
  {
    AuthenticatedAppCommunityGroupIdRoute:
      AuthenticatedAppCommunityGroupIdRoute,
  }

const AuthenticatedAppCommunityRouteWithChildren =
  AuthenticatedAppCommunityRoute._addFileChildren(
    AuthenticatedAppCommunityRouteChildren,
  )

interface AuthenticatedAppMessagesRouteChildren {
  AuthenticatedAppMessagesUserIdRoute: typeof AuthenticatedAppMessagesUserIdRoute
}

const AuthenticatedAppMessagesRouteChildren: AuthenticatedAppMessagesRouteChildren =
  {
    AuthenticatedAppMessagesUserIdRoute: AuthenticatedAppMessagesUserIdRoute,
  }

const AuthenticatedAppMessagesRouteWithChildren =
  AuthenticatedAppMessagesRoute._addFileChildren(
    AuthenticatedAppMessagesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppChallengesRoute: typeof AuthenticatedAppChallengesRouteWithChildren
  AuthenticatedAppCofoundersRoute: typeof AuthenticatedAppCofoundersRouteWithChildren
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRouteWithChildren
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFeedRoute: typeof AuthenticatedAppFeedRoute
  AuthenticatedAppHallRoute: typeof AuthenticatedAppHallRoute
  AuthenticatedAppIdeasRoute: typeof AuthenticatedAppIdeasRoute
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppMessagesRoute: typeof AuthenticatedAppMessagesRouteWithChildren
  AuthenticatedAppOnboardingRoute: typeof AuthenticatedAppOnboardingRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppResourcesRoute: typeof AuthenticatedAppResourcesRoute
  AuthenticatedAppShowcaseRoute: typeof AuthenticatedAppShowcaseRoute
  AuthenticatedAppUUserIdRoute: typeof AuthenticatedAppUUserIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppChallengesRoute: AuthenticatedAppChallengesRouteWithChildren,
  AuthenticatedAppCofoundersRoute: AuthenticatedAppCofoundersRouteWithChildren,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRouteWithChildren,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFeedRoute: AuthenticatedAppFeedRoute,
  AuthenticatedAppHallRoute: AuthenticatedAppHallRoute,
  AuthenticatedAppIdeasRoute: AuthenticatedAppIdeasRoute,
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppMessagesRoute: AuthenticatedAppMessagesRouteWithChildren,
  AuthenticatedAppOnboardingRoute: AuthenticatedAppOnboardingRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppResourcesRoute: AuthenticatedAppResourcesRoute,
  AuthenticatedAppShowcaseRoute: AuthenticatedAppShowcaseRoute,
  AuthenticatedAppUUserIdRoute: AuthenticatedAppUUserIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
